name: pharaoh_rate_limit
description: Rate limiting middleware for Pharaoh web framework with token bucket and sliding window algorithms
version: 1.0.0
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/pharaoh_rate_limit

environment:
  sdk: ^3.0.0

dependencies:
  pharaoh: ^0.0.8+3
  meta: ^1.15.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  spookie:
